apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mario
    path: ../../helms/mario
    valuesFile: dev-values.yaml
    namespace: dev  # Set your target namespace
